### ISSUE TITLE
Syntax errors

### ISSUE THREAD

**Issue by JakeHedman** [bijoutrouvaille/fireward#11]
The following examples all work in the firestore emulator but crashes fireward:

```firestore
function test (a,b) {
  return true
}

match /test/test {
  allow read: if test(true, 'asdf');
}
```

```firestore
match /test/test {
  allow read: if data().keys().hasAll(['a', 'b', 'c']);
}
```

```firestore
function b () {
  return "adsf"
}
match /test/{a} {
  allow read: if exists(/test/$(a)/$(b())/$(b(a)))
}
```

```firestore
match /test/{a} {
  allow read
}
```

**Comment by JakeHedman** [comment]
Found most of these in my own security rules, but also tested a bunch of public security rules from github and most of them fail due to some of the bugs mentioned, or because of functions starting with "is".

Maybe the is-problem should be looked at to make the transition to fireward easier. Having to remove the boilerplate also seems like an unnecessary extra step.

https://github.com/search?utf8=%E2%9C%93&q=+language%3A%22Cloud+Firestore+Security+Rules%22+delete+hasall+size%3A%3E5000&type=Code

**Comment by bijoutrouvaille** [comment]
Thanks Jake. These are serious issues and probably came from the switch to the new expression parser. Unfortunately I won’t  have much internet until Monday, and won’t be able to fix until then. If your work needs it now, I can suggest interim workarounds. Lmk

**Comment by JakeHedman** [comment]
@bijoutrouvaille: No sweat! I can work around it for now. :) And thanks for the quick response, love the project!

**Comment by bijoutrouvaille** [comment]
@JakeHedman what do you mean by the "is-problem" ? I don't understand what that github search is about.

**Comment by bijoutrouvaille** [comment]
Never mind, I missed part of the comment. I think the is-problem was fixed with one of the recent versions. Currently the generated function names look like this `is____User` (with 4 underscores).

**Comment by bijoutrouvaille** [comment]
Issues should be fixed in v 1.1.1 available on NPM and in releases.

**Comment by JakeHedman** [comment]
@bijoutrouvaille Thanks! It all works now (including is-functions). I found some other problems but I'll create a new issue for those :)

**Comment by bijoutrouvaille** [comment]
@JakeHedman what do you mean by "having to remove the boilerplate" ? Can you please elaborate on what the boilerplate is, who needs to remove it and why?
