### ISSUE TITLE
Support GeoPoint

### ISSUE THREAD

**Issue by mackattack3k** [bijoutrouvaille/fireward#19]
Do you have any plans to support GeoPoint type validating?

Unfortunately there is no support for it in firestore rules natively although there is a [GeoPoint](https://firebase.google.com/docs/reference/android/com/google/firebase/firestore/GeoPoint) type in firestore.

I have tried using a custom type as an object but that doesn't seem to work. I also tried to type it as `any` but seems like that support isn't there either?

**Comment by bijoutrouvaille** [comment]
Thanks for the request. The geopoint and any support should be easy to implement. I'll look into it this weekend.

**Comment by mackattack3k** [comment]
Maybe it should be implemented with `is latlng` somehow?

Awesome work with fireward!

**Comment by bijoutrouvaille** [comment]
Thanks! Yes, I plan to use their built-in type.

**Comment by bijoutrouvaille** [comment]
Geo types and any should now be available in 1.4.3 on all release channels. TS should generate a `WardGeoPoint` type, and firestore should be checking for the built-in `latlng`. Thanks for reporting.

**Comment by toddpi314** [comment]
Um, this is one of the most useful tools for firestore right now. Thanks for the quick support adding features like this, and keep up the good work.
