### ISSUE TITLE
Support for TS Record Type with known value type

### ISSUE THREAD

**Issue by glumb** [bijoutrouvaille/fireward#20]
I'm using the ts record type for structuring user references:
```ts
type UserReferences = Record<string, UserReference> // { usr_id: {roles: ['a'] } }
```

Currently only `Record<string, unknown>` is supported by using `map`. This won't validate the entries of the map though.

Is it possible to add typed Record functionality?

**Comment by bijoutrouvaille** [comment]
@glumb I’m afraid that isn’t possible. Last I checked, firestore rules don’t allow for iteration, so we can’t verify contents of arrays and records.

**Comment by glumb** [comment]
I wrote some custom logic to "iterate" the object by hardcoding the indices, similar to tuple logic. 

```ts 
type UserReferences = {
  // [key: string]: UserReference

  allow create, update:  (data!=null && data is list && data.size() < 4)
          && data.size() > 0 && is____UserReference(data.values()[0])
          && data.size() > 1 && is____UserReference(data.values()[1])
          && data.size() > 2 && is____UserReference(data.values()[2])
}
```
However it is not possible to generate the ts types accordingly, since ` [key: string]: UserReference` fails compiling. How should custom logic for ts and Firestore be mixed?

**Comment by bijoutrouvaille** [comment]
@glumb I am open to ideas, but this seems like something that cannot be handled on the type level. I don't even know how this kind of data type (associative tuple?) could be implemented in TypeScript.

The generic version of this problem—a type with custom validation logic—is not solvable using a single type definition, in my understanding. You would have to implement this logic on the domain (business logic) level. In plainer language: you’ll need to validate user input.
