### ISSUE TITLE
Support more common types such as email and url

### ISSUE THREAD

**Issue by searchableguy** [bijoutrouvaille/fireward#22]
I think those two are fairly common types which aren't natively supported by firebase.

PS: are there protected fields and default values?

**Comment by bijoutrouvaille** [comment]
@searchableguy Thanks for the suggestion. Both email and URL have an extremely complicated spec. Most applications don't need the entire spec, so validating there is easy, but creating generic validators that would work for everyone would create support requirements beyond the means of this project. Another reason against it is that Fireward aims to maintain an isomorphic relationship between static types (currently only in Typescript) and Firestore rule logic. Email and URL spec is not possible to validate using static types.


"are there protected fields and default values" 
You cannot assign values in the rules, so we cannot have default values. Regarding protected fields, you can have the option of const values and [type validation expressions](https://github.com/bijoutrouvaille/fireward#complete-example).
