### ISSUE TITLE
Create an NPM package

### ISSUE THREAD

**Issue by bijoutrouvaille** [bijoutrouvaille/fireward#3]
Investigate the possibility to distribute executables to avoid compiling of Haskell on each machine.

**Comment by idolize** [comment]
It may be worth looking at how "npm packages" like [`flow-bin`](https://github.com/flowtype/flow-bin) distribute compiled binaries as packages

**Comment by bijoutrouvaille** [comment]
Thanks for the relevant link. From what I gather, the flow-bin package simply uploads to NPM all the binary distributions of flow from flow's main releases page. I imagine the multi-platform build is done via their CI.

CircleCI offers free service to open source projects for Linux and Mac. They might even have Windows support soon. I'll look into it when I have a little time.

**Comment by tohagan** [comment]
You could also translate your Haskell into Javascript and deploy that!
- [Haskell to JavaScript compiler, based on GHC](https://github.com/ghcjs/ghcjs)

**Comment by bijoutrouvaille** [comment]
Thanks @tohagan . I'm probably not going to do that since it would create a bloated and slow package. One of many advantages of Haskell is that it compiles to machine code.

BTW, the Facebook Flow compiler is written in OCaml, which is from the same language family, which signals to me that Haskell was not a terrible choice for this project.

**Comment by bijoutrouvaille** [comment]
https://discuss.circleci.com/t/multiple-os-compilation-targets-for-an-open-source-project/32108

**Comment by bijoutrouvaille** [comment]
Another update. Circle replied to the forum post above, and I wrote the config file for a multi-platform CI build workflow to upload as an NPM package. Circle threw an error that "Resource class windows.medium for machine is not available for your project." Their docs tell you that in order to set the resource class, a support ticket has to be opened with them, which is what I've done.

FYI, the NPM package `fireward` currently up on npmjs.com is just a wrapper and will do nothing because it lacks the binaries.

**Comment by tohagan** [comment]
For the record ... I don't disagree with your choice of Haskell to implement a compiler. Years ago I coded a mini "C" compiler in a week using Miranda - a predecessor to Haskell - so I "get it".

**Comment by bijoutrouvaille** [comment]
@tohagan that's cool. 

It's no longer a problem though. We're almost there with the binaries, as you can see from the releases page. Travis is set up to upload the binaries for the three platforms. The only thing left is to put them all together into an npm package.

**Comment by tohagan** [comment]
Excellent!  Thanks for your hard work.

**Comment by bijoutrouvaille** [comment]
`npm install fireward` now should work
