### ISSUE TITLE
Clarification on update validations

### ISSUE THREAD

**Issue by henrymoulton** [bijoutrouvaille/fireward#34]
From docs:

> Note: if a validation is absent for a method and type, it will pass. For example, if you have create and delete validations, but not an update one, updates will pass validation, unless other conditions (e.g. route-level conditions or variable type validation) prevent it.

Does this mean it is not really possible to `updates` with validation as you would (often) have to provide the entire object to ensure all keys are valid?

e.g 

```
type UserDoc = {
    name: string,
    verified: bool,
    email: string,
    photoURL: string | null
    teams?: string[]
}

match /users/{userId} is UserDoc {
  allow read: if isLoggedInUser(userId);
  allow create, update: if isLoggedInUser(userId);
  allow delete: false;
}

await firestore()
        .doc(`users/${userId}`)
        .update({
          teams: [...userData?.teams, docRef.id],
        } as Pick<UserDoc, "teams">); // Will fail as isn't a valid UserDoc
```

At the moment is a fix something like:

```
match /users/{userId} is UserDoc {
  allow read: if isLoggedInUser(userId);
  allow create if isLoggedInUser(userId); // remove update
  allow delete: false;
}

match /users/{userId} {
  allow update: if isLoggedInUser(userId); 
}
```

Or is there an alternative data structure that might be better?

**Comment by henrymoulton** [comment]
Thanks for the library @bijoutrouvaille I'm back to using it again :D

**Comment by bijoutrouvaille** [comment]
@henrymoulton thanks for using the library! If I'm understanding you correctly, updates performed with the `firestore().update` method get their partial payload object merged with the full object in the database before they are presented to the rules, so your first example should work just fine. This a Firestore not a Fireward feature.

**Comment by henrymoulton** [comment]
Ah good knowledge, thanks for clarifying.
