### ISSUE TITLE
A few ideas

### ISSUE THREAD

**Issue by henrymoulton** [bijoutrouvaille/fireward#35]
Here's my current script:

```
#!/usr/bin/env bash

echo "Combining all files Fireward files"
tmpfile=$(mktemp rules-combined.ward)
cat team.ward >> rules-combined.ward
cat user.ward >> rules-combined.ward

echo "Generating Firebase Rules"
fireward -i rules-combined.ward > firestore.rules

echo "Generating Typescript Types"
fireward -i rules-combined.ward --lang=typescript > CrewcartTypes.ts

echo "Making Typescript Types Prettier"
tmpfile2=$(mktemp prettier-types.ts)
prettier CrewcartTypes.ts > prettier-types.ts
cp -f prettier-types.ts CrewcartTypes.ts
rm "$tmpfile"
rm "$tmpfile2"
echo "Done"

echo "Copying across monorepo"
node ./copy-types.js
```

It has the following "features":
- Split files by Entity (Otherwise I fear I'll run into a massive file, however this means I might have some type duplication as there's no import system, not sure if this is an issue.)
- Using Prettier on the output

Let me know if you have any thoughts on these!

I'm also thinking about adding Watchman or something to run the script on edit to then put the types in my functions/app (if anyone has a good guide for a single place please let me know).

**Comment by bijoutrouvaille** [comment]
Apologies for the late reply @henrymoulton. This looks like a very succinct way to handle the problem of large files. 

"I might have some type duplication as there's no import system, not sure if this is an issue"

Currently, Fireward does not analyze the system for duplicate types, so whether you have one file or many, it is currently up to you to make sure to avoid duplication. I'll put this on the todo, however, as it seems like an easy enhancement that can prevent a lot of headache.

"I'm also thinking about adding Watchman"

Watchman is a good solution. I personally use make files, which only trigger a rebuild if the output file is outdated, in tandem with the `watch` command to trigger the make target every second. Unfortunately Haskell doesn't come with a file watcher built in, and so far we've managed to avoid external dependencies, so a watch mode isn't planned yet.
