### ISSUE TITLE
can't figure out how to write validations for atomic types

### ISSUE THREAD

**Issue by jmagaram** [bijoutrouvaille/fireward#39]
This works...

    type Email = { 
        address: string, 
        verified: bool

        allow write, update: 
            if data.address.matches("^\Ssomeexpression$") 
    }

But can't figure out how to write validation rules for aliases like...

    type UserId = string
    allow write, update: if data != ""

    type EmailAddress = string
    allow write, update: if data.matches("^\Ssomeexpression$")

=== 

Found a workaround...a global validator like `IsUserIdValid(...)` and `IsEmailAddressValid(...)` and call those within the more complex objects. Would be nicer though to have validators on the atomic data types.

**Comment by bijoutrouvaille** [comment]
@jmagaram Another great point. Atomic type validations are already on the unofficial roadmap.

**Comment by jmagaram** [comment]
ok thanks.
