### ISSUE TITLE
How to define map (nested object with variable key names)

### ISSUE THREAD

**Issue by kamilbiela** [bijoutrouvaille/fireward#7]
I would like o define an object map, equivalent of typescript:
```
{[key: string]: boolean}
```
But I can't seem to make it work, is it supported?

Use case: map of accesses  to other objects on user object, i.e:
```
type User = {
  name: "test name"
  access_to: {
    someid1: true,
    someid3: true,
    ...etc
  }
}
```
I dont want to use subcollections, because I will have here at most 4 entries.

**Comment by kamilbiela** [comment]
I didn't program in haskell ever, so not sure if that's really the case, but after looking in code it seems that there is no support for 'map' type, 

https://github.com/google/cel-spec/blob/master/doc/langdef.md#values

https://stackoverflow.com/questions/48051692/how-to-enforce-values-in-a-map-in-firestore-rules-without-knowing-the-keys

**Comment by bijoutrouvaille** [comment]
Are you looking for something like this (not sure if this is valid syntax, since writeFields seem to be on the way out)?

```
allow update: if request.auth != null
     && request.resource.data.users is map
     && (request.auth.uid in request.resource.data.users.access_to)
     && request.resource.data.users.access_to[request.auth.uid] == true;
```

**Comment by bijoutrouvaille** [comment]
If so, I don't think I've implemented maps, but I'll look into it this weekend.

**Comment by bijoutrouvaille** [comment]
Version `0.0.9` now has the map type. Confirmed to work in the simulator. Please report issues if you experience them.

**Comment by kamilbiela** [comment]
Great thanks, works like a charm
